name: Android Publish Release

on:
  release:
    types: [published]

jobs:

  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew library:build
      - name: Run Unit tests
        run: bash ./gradlew library:testReleaseUnitTest --stacktrace
      - name: Publish artifact
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}

        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GPR_USER}"
          ./gradlew -Pversion=${NEW_VERSION} library:publish
